version: '3.8'

services:
  api:
    build: .
    ports:
      - "3000:3000"
    env_file:
      - .env
    volumes:
      - .:/api
      - /api/node_modules
    depends_on:
      - db
    command: ["npm", "run", "start"]
  db:
    image: postgres:16
    ports:
      - "5432:5432"
    environment:
      POSTGRES_USER: ${DB_USER}
      POSTGRES_PASSWORD: ${DB_PASSWORD}
      POSTGRES_DB: ${DB_NAME}
    volumes:
      - ./db.sql:/docker-entrypoint-initdb.d/db.sql
      - pgdata:/var/lib/postgresql/data

volumes:
  pgdata: